$schema: https://json-schema.org/draft/2020-12/schema
$id: https://raw.githubusercontent.com/DataDog/schema/main/agent/snmp_listener.yaml.schema.json
node_type: section
type: object
properties:
  allowed_failures:
    node_type: setting
    type: number
    default: 3
    tags:
    - golang_type:int
  collect_device_metadata:
    node_type: setting
    type: boolean
    default: true
  collect_topology:
    node_type: setting
    type: boolean
    default: true
  configs:
    node_type: setting
    type: array
    default: []
    items:
      type: object
  discovery_allowed_failures:
    node_type: setting
    type: number
    default: 3
    tags:
    - golang_type:int
  discovery_interval:
    node_type: setting
    type: number
    default: 3600
    tags:
    - golang_type:int
  loader:
    node_type: setting
    type: string
    default: core
  min_collection_interval:
    node_type: setting
    type: number
    default: 15
    tags:
    - golang_type:int
  namespace:
    node_type: setting
    type: string
    default: default
  oid_batch_size:
    node_type: setting
    type: number
    default: 5
    tags:
    - golang_type:int
  ping:
    node_type: section
    type: object
    properties:
      count:
        node_type: setting
        type: number
        default: 2
        tags:
        - golang_type:int
      enabled:
        node_type: setting
        type: boolean
        default: false
      interval:
        node_type: setting
        type: number
        default: 10
        tags:
        - golang_type:int
      linux:
        node_type: section
        type: object
        properties:
          use_raw_socket:
            node_type: setting
            type: boolean
            default: false
      timeout:
        node_type: setting
        type: number
        default: 3000
        tags:
        - golang_type:int
  retries:
    node_type: setting
    type: number
    default: 3
    tags:
    - golang_type:int
  timeout:
    node_type: setting
    type: number
    default: 5
    tags:
    - golang_type:int
  use_device_id_as_hostname:
    node_type: setting
    type: boolean
    default: false
  workers:
    node_type: setting
    type: number
    default: 2
    tags:
    - golang_type:int
