// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-present Datadog, Inc.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: datadog/remoteagent/healthissues.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthIssueProvider_GetHealthIssues_FullMethodName = "/datadog.remoteagent.healthissues.v1.HealthIssueProvider/GetHealthIssues"
)

// HealthIssueProviderClient is the client API for HealthIssueProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthIssueProviderClient interface {
	// Gets all currently active health issues of a remote agent.
	GetHealthIssues(ctx context.Context, in *GetHealthIssuesRequest, opts ...grpc.CallOption) (*GetHealthIssuesResponse, error)
}

type healthIssueProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthIssueProviderClient(cc grpc.ClientConnInterface) HealthIssueProviderClient {
	return &healthIssueProviderClient{cc}
}

func (c *healthIssueProviderClient) GetHealthIssues(ctx context.Context, in *GetHealthIssuesRequest, opts ...grpc.CallOption) (*GetHealthIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthIssuesResponse)
	err := c.cc.Invoke(ctx, HealthIssueProvider_GetHealthIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthIssueProviderServer is the server API for HealthIssueProvider service.
// All implementations must embed UnimplementedHealthIssueProviderServer
// for forward compatibility.
type HealthIssueProviderServer interface {
	// Gets all currently active health issues of a remote agent.
	GetHealthIssues(context.Context, *GetHealthIssuesRequest) (*GetHealthIssuesResponse, error)
	mustEmbedUnimplementedHealthIssueProviderServer()
}

// UnimplementedHealthIssueProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthIssueProviderServer struct{}

func (UnimplementedHealthIssueProviderServer) GetHealthIssues(context.Context, *GetHealthIssuesRequest) (*GetHealthIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthIssues not implemented")
}
func (UnimplementedHealthIssueProviderServer) mustEmbedUnimplementedHealthIssueProviderServer() {}
func (UnimplementedHealthIssueProviderServer) testEmbeddedByValue()                             {}

// UnsafeHealthIssueProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthIssueProviderServer will
// result in compilation errors.
type UnsafeHealthIssueProviderServer interface {
	mustEmbedUnimplementedHealthIssueProviderServer()
}

func RegisterHealthIssueProviderServer(s grpc.ServiceRegistrar, srv HealthIssueProviderServer) {
	// If the following call pancis, it indicates UnimplementedHealthIssueProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthIssueProvider_ServiceDesc, srv)
}

func _HealthIssueProvider_GetHealthIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthIssueProviderServer).GetHealthIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthIssueProvider_GetHealthIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthIssueProviderServer).GetHealthIssues(ctx, req.(*GetHealthIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthIssueProvider_ServiceDesc is the grpc.ServiceDesc for HealthIssueProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthIssueProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datadog.remoteagent.healthissues.v1.HealthIssueProvider",
	HandlerType: (*HealthIssueProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealthIssues",
			Handler:    _HealthIssueProvider_GetHealthIssues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datadog/remoteagent/healthissues.proto",
}
