// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-present Datadog, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: datadog/remoteagent/healthissues.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthIssuesRequest) Reset() {
	*x = GetHealthIssuesRequest{}
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthIssuesRequest) ProtoMessage() {}

func (x *GetHealthIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthIssuesRequest.ProtoReflect.Descriptor instead.
func (*GetHealthIssuesRequest) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_healthissues_proto_rawDescGZIP(), []int{0}
}

type HealthIssueReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique instance id, used as the store's map key in the core agent.
	IssueId string `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	// Template id looked up in the core agent's issue registry.
	IssueType string `protobuf:"bytes,2,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	// Reporting integration or component name.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Variables for filling in the issue template.
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Extra tags appended to the template's defaults.
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthIssueReport) Reset() {
	*x = HealthIssueReport{}
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthIssueReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthIssueReport) ProtoMessage() {}

func (x *HealthIssueReport) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthIssueReport.ProtoReflect.Descriptor instead.
func (*HealthIssueReport) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_healthissues_proto_rawDescGZIP(), []int{1}
}

func (x *HealthIssueReport) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *HealthIssueReport) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *HealthIssueReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HealthIssueReport) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *HealthIssueReport) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetHealthIssuesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All currently active health issues on this remote agent.
	// An empty list means the agent is healthy (no active issues).
	Issues        []*HealthIssueReport `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthIssuesResponse) Reset() {
	*x = GetHealthIssuesResponse{}
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthIssuesResponse) ProtoMessage() {}

func (x *GetHealthIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datadog_remoteagent_healthissues_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthIssuesResponse.ProtoReflect.Descriptor instead.
func (*GetHealthIssuesResponse) Descriptor() ([]byte, []int) {
	return file_datadog_remoteagent_healthissues_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealthIssuesResponse) GetIssues() []*HealthIssueReport {
	if x != nil {
		return x.Issues
	}
	return nil
}

var File_datadog_remoteagent_healthissues_proto protoreflect.FileDescriptor

const file_datadog_remoteagent_healthissues_proto_rawDesc = "" +
	"\n" +
	"&datadog/remoteagent/healthissues.proto\x12#datadog.remoteagent.healthissues.v1\"\x18\n" +
	"\x16GetHealthIssuesRequest\"\x94\x02\n" +
	"\x11HealthIssueReport\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x02 \x01(\tR\tissueType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12]\n" +
	"\acontext\x18\x04 \x03(\v2C.datadog.remoteagent.healthissues.v1.HealthIssueReport.ContextEntryR\acontext\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x17GetHealthIssuesResponse\x12N\n" +
	"\x06issues\x18\x01 \x03(\v26.datadog.remoteagent.healthissues.v1.HealthIssueReportR\x06issues2\xa4\x01\n" +
	"\x13HealthIssueProvider\x12\x8c\x01\n" +
	"\x0fGetHealthIssues\x12;.datadog.remoteagent.healthissues.v1.GetHealthIssuesRequest\x1a<.datadog.remoteagent.healthissues.v1.GetHealthIssuesResponseB\x15Z\x13pkg/proto/pbgo/coreb\x06proto3"

var (
	file_datadog_remoteagent_healthissues_proto_rawDescOnce sync.Once
	file_datadog_remoteagent_healthissues_proto_rawDescData []byte
)

func file_datadog_remoteagent_healthissues_proto_rawDescGZIP() []byte {
	file_datadog_remoteagent_healthissues_proto_rawDescOnce.Do(func() {
		file_datadog_remoteagent_healthissues_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_healthissues_proto_rawDesc), len(file_datadog_remoteagent_healthissues_proto_rawDesc)))
	})
	return file_datadog_remoteagent_healthissues_proto_rawDescData
}

var file_datadog_remoteagent_healthissues_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datadog_remoteagent_healthissues_proto_goTypes = []any{
	(*GetHealthIssuesRequest)(nil),  // 0: datadog.remoteagent.healthissues.v1.GetHealthIssuesRequest
	(*HealthIssueReport)(nil),       // 1: datadog.remoteagent.healthissues.v1.HealthIssueReport
	(*GetHealthIssuesResponse)(nil), // 2: datadog.remoteagent.healthissues.v1.GetHealthIssuesResponse
	nil,                             // 3: datadog.remoteagent.healthissues.v1.HealthIssueReport.ContextEntry
}
var file_datadog_remoteagent_healthissues_proto_depIdxs = []int32{
	3, // 0: datadog.remoteagent.healthissues.v1.HealthIssueReport.context:type_name -> datadog.remoteagent.healthissues.v1.HealthIssueReport.ContextEntry
	1, // 1: datadog.remoteagent.healthissues.v1.GetHealthIssuesResponse.issues:type_name -> datadog.remoteagent.healthissues.v1.HealthIssueReport
	0, // 2: datadog.remoteagent.healthissues.v1.HealthIssueProvider.GetHealthIssues:input_type -> datadog.remoteagent.healthissues.v1.GetHealthIssuesRequest
	2, // 3: datadog.remoteagent.healthissues.v1.HealthIssueProvider.GetHealthIssues:output_type -> datadog.remoteagent.healthissues.v1.GetHealthIssuesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_datadog_remoteagent_healthissues_proto_init() }
func file_datadog_remoteagent_healthissues_proto_init() {
	if File_datadog_remoteagent_healthissues_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datadog_remoteagent_healthissues_proto_rawDesc), len(file_datadog_remoteagent_healthissues_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datadog_remoteagent_healthissues_proto_goTypes,
		DependencyIndexes: file_datadog_remoteagent_healthissues_proto_depIdxs,
		MessageInfos:      file_datadog_remoteagent_healthissues_proto_msgTypes,
	}.Build()
	File_datadog_remoteagent_healthissues_proto = out.File
	file_datadog_remoteagent_healthissues_proto_goTypes = nil
	file_datadog_remoteagent_healthissues_proto_depIdxs = nil
}
