"""Generate build-tag data for Bazel consumers from tasks/build_tags.py.

The source of truth is the Python module; this repo rule shells out to
`dda inv codegen-to-json`, parses the structured payload, and emits a single
generated file consumed by the root BUILD.bazel:

  - gazelle_build_tags.bzl   load()ed by //:BUILD.bazel to feed gazelle's
                             build_tags argument.

Downstream branches that need the per-flavor tag sets (e.g. for a flavored
dd_agent_go_test wrapper) can extend this rule to emit additional files
(flavors.bzl, tags.go, ...) reading from the same JSON payload.

Usage in MODULE.bazel:
    build_tags_codegen = use_repo_rule("//bazel/repo:build_tags_codegen.bzl", "build_tags_codegen")
    build_tags_codegen(name = "dd_build_tags_codegen")

    load("@dd_build_tags_codegen//:gazelle_build_tags.bzl", "GAZELLE_BUILD_TAGS")
"""

_BUILD_FILE_CONTENT = """
exports_files(
    ["gazelle_build_tags.bzl"],
    visibility = ["//visibility:public"],
)
"""

_BZL_HEADER = """# Code generated by //bazel/repo:build_tags_codegen.bzl from tasks/build_tags.py. DO NOT EDIT.
"""

def _bzl_str_list(values):
    return "[" + ", ".join(['"%s"' % v for v in values]) + "]"

def _render_gazelle_bzl(data):
    return _BZL_HEADER + "GAZELLE_BUILD_TAGS = " + _bzl_str_list(data["gazelle_build_tags"]) + "\n"

def _impl(rctx):
    # Re-run the rule whenever any of these change. Without watch(), edits to
    # tasks/build_tags.py wouldn't trigger regeneration on subsequent builds.
    rctx.watch(rctx.attr._build_tags_py)
    rctx.watch(rctx.attr._flavor_py)
    rctx.watch(rctx.attr._init_py)

    # The codegen task writes JSON to a file rather than stdout so we don't
    # have to parse around dda/rich's console init noise on Windows.
    out_file = rctx.path("payload.json")
    result = rctx.execute(
        ["dda", "inv", "codegen-to-json", "--output=" + str(out_file)],
        working_directory = str(rctx.workspace_root),
        quiet = True,
    )
    if result.return_code != 0:
        fail("dda inv codegen-to-json failed (rc=%d):\nstdout=%s\nstderr=%s" %
             (result.return_code, result.stdout, result.stderr))

    data = json.decode(rctx.read(out_file))

    rctx.file("BUILD.bazel", _BUILD_FILE_CONTENT)
    rctx.file("gazelle_build_tags.bzl", _render_gazelle_bzl(data))

build_tags_codegen = repository_rule(
    implementation = _impl,
    doc = "Generate build-tag data for Bazel from tasks/build_tags.py.",
    attrs = {
        "_build_tags_py": attr.label(default = "//tasks:build_tags.py", allow_single_file = True),
        "_flavor_py": attr.label(default = "//tasks:flavor.py", allow_single_file = True),
        "_init_py": attr.label(default = "//tasks:__init__.py", allow_single_file = True),
    },
)
