"""Generate build-tag data for Bazel consumers from tasks/build_tags.py.

The source of truth is the Python module; this repo rule shells out to
`dda inv codegen-to-json`, parses the structured payload, and emits three
generated files:

  - gazelle_build_tags.bzl   load()ed by //:BUILD.bazel to feed gazelle's
                             build_tags argument.
  - flavors.bzl              per-flavor tag sets + platform composition
                             inputs, load()ed by //bazel/flavors:defs.bzl.
  - tags.go                  same per-flavor data exposed to Go, embedded
                             in //bazel/rules/dd_agent_go_test:gazelle_extension.

Usage in MODULE.bazel:
    build_tags_codegen = use_repo_rule("//bazel/repo:build_tags_codegen.bzl", "build_tags_codegen")
    build_tags_codegen(name = "dd_build_tags_codegen")

    load("@dd_build_tags_codegen//:gazelle_build_tags.bzl", "GAZELLE_BUILD_TAGS")
    load("@dd_build_tags_codegen//:flavors.bzl", "FLAVOR_UNIT_TEST_TAGS", ...)
"""

_BUILD_FILE_CONTENT = """
exports_files(
    [
        "flavors.bzl",
        "gazelle_build_tags.bzl",
        "tags.go",
    ],
    visibility = ["//visibility:public"],
)
"""

_GO_HEADER = """// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026-present Datadog, Inc.

// Code generated by //bazel/repo:build_tags_codegen.bzl from tasks/build_tags.py. DO NOT EDIT.

package dd_agent_go_test
"""

_BZL_HEADER = """# Code generated by //bazel/repo:build_tags_codegen.bzl from tasks/build_tags.py. DO NOT EDIT.
"""

def _bzl_str_list(values):
    return "[" + ", ".join(['"%s"' % v for v in values]) + "]"

def _render_gazelle_bzl(data):
    return _BZL_HEADER + "GAZELLE_BUILD_TAGS = " + _bzl_str_list(data["gazelle_build_tags"]) + "\n"

def _render_flavors_bzl(data):
    lines = [_BZL_HEADER]
    for name in ("COMMON_TAGS", "UNIT_TEST_TAGS", "LINUX_ONLY_TAGS",
                 "WINDOWS_INCLUDED_TAGS", "WINDOWS_EXCLUDED_TAGS",
                 "DARWIN_EXCLUDED_TAGS"):
        lines.append("%s = %s" % (name, _bzl_str_list(data[name.lower()])))
    lines.append("")
    # FLAVOR_UNIT_TEST_TAGS = flavor_specific + COMMON_TAGS + UNIT_TEST_TAGS.
    # Materialized here (rather than computed in the consuming .bzl) so the
    # consumer is a thin shim.
    lines.append("FLAVOR_UNIT_TEST_TAGS = {")
    common = data["common_tags"]
    unit = data["unit_test_tags"]
    for flavor in sorted(data["flavor_specific_tags"].keys()):
        merged = sorted(set(data["flavor_specific_tags"][flavor] + common + unit))
        lines.append('    "%s": %s,' % (flavor, _bzl_str_list(merged)))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)

def _go_str_list(values):
    return "[]string{" + ", ".join(['"%s"' % v for v in values]) + "}"

def _render_tags_go(data):
    lines = [_GO_HEADER]
    lines.append("")
    lines.append("var commonTags = %s" % _go_str_list(data["common_tags"]))
    lines.append("")
    lines.append("var unitTestTags = %s" % _go_str_list(data["unit_test_tags"]))
    lines.append("")
    lines.append("var flavorSpecificTags = map[string][]string{")
    for flavor in sorted(data["flavor_specific_tags"].keys()):
        lines.append('\t"%s": %s,' % (flavor, _go_str_list(data["flavor_specific_tags"][flavor])))
    lines.append("}")
    lines.append("")
    lines.append("// FlavorUnitTestTags is the per-flavor tag set the Gazelle extension uses")
    lines.append("// to decide which dd_agent_go_test variants apply to a package's srcs.")
    lines.append("var FlavorUnitTestTags = func() map[string][]string {")
    lines.append("\tout := make(map[string][]string, len(flavorSpecificTags))")
    lines.append("\tfor flavor, specific := range flavorSpecificTags {")
    lines.append("\t\ttags := make([]string, 0, len(specific)+len(commonTags)+len(unitTestTags))")
    lines.append("\t\ttags = append(tags, specific...)")
    lines.append("\t\ttags = append(tags, commonTags...)")
    lines.append("\t\ttags = append(tags, unitTestTags...)")
    lines.append("\t\tout[flavor] = tags")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}()")
    lines.append("")
    return "\n".join(lines)

def _impl(rctx):
    # Re-run the rule whenever any of these change. Without watch(), edits to
    # tasks/build_tags.py wouldn't trigger regeneration on subsequent builds.
    rctx.watch(rctx.attr._build_tags_py)
    rctx.watch(rctx.attr._flavor_py)
    rctx.watch(rctx.attr._init_py)

    # The codegen task writes JSON to a file rather than stdout so we don't
    # have to parse around dda/rich's console init noise on Windows.
    out_file = rctx.path("payload.json")
    result = rctx.execute(
        ["dda", "inv", "codegen-to-json", "--output=" + str(out_file)],
        working_directory = str(rctx.workspace_root),
        quiet = True,
    )
    if result.return_code != 0:
        fail("dda inv codegen-to-json failed (rc=%d):\nstdout=%s\nstderr=%s" %
             (result.return_code, result.stdout, result.stderr))

    data = json.decode(rctx.read(out_file))

    rctx.file("BUILD.bazel", _BUILD_FILE_CONTENT)
    rctx.file("flavors.bzl", _render_flavors_bzl(data))
    rctx.file("gazelle_build_tags.bzl", _render_gazelle_bzl(data))
    rctx.file("tags.go", _render_tags_go(data))

build_tags_codegen = repository_rule(
    implementation = _impl,
    doc = "Generate build-tag data for Bazel from tasks/build_tags.py.",
    attrs = {
        "_build_tags_py": attr.label(default = "//tasks:build_tags.py", allow_single_file = True),
        "_flavor_py": attr.label(default = "//tasks:flavor.py", allow_single_file = True),
        "_init_py": attr.label(default = "//tasks:__init__.py", allow_single_file = True),
    },
)
