"""Bazel entry point for //bazel/build_tags_codegen:build_tags_codegen.

Invoked by the run_binary action in this package. Writes the generated
GAZELLE_BUILD_TAGS .bzl to the path given in argv[1].

The payload itself lives in tasks/libs/common/build_tags.py — that's
the build_tags library both this script and the dda inv `codegen-to-json`
task read from. This module owns only the .bzl rendering, which is
Bazel-specific.
"""

from __future__ import annotations

import sys

from tasks.libs.common.build_tags import build_tags_codegen_payload


def render_gazelle_build_tags_bzl(payload: dict) -> str:
    """Render the GAZELLE_BUILD_TAGS .bzl file consumed by the root BUILD.bazel.

    Output is buildifier-compatible (multi-line list with trailing commas) so
    re-running buildifier on the committed file is a no-op.
    """
    lines = [
        "# Code generated by //bazel/build_tags_codegen:build_tags_codegen from",
        "# tasks/libs/common/build_tags.py. DO NOT EDIT.",
        "",
        "GAZELLE_BUILD_TAGS = [",
    ]
    for tag in payload["gazelle_build_tags"]:
        lines.append(f'    "{tag}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <output.bzl>")
    with open(sys.argv[1], "w") as f:
        f.write(render_gazelle_build_tags_bzl(build_tags_codegen_payload()))


if __name__ == "__main__":
    main()
